### PR TITLE
rr/enhacement-padding-menu-item

### PR DESCRIPTION
**Pull request by betorobson**
added padding left menu-item inside a panel.

From this:
screenshot from 2018-01-11 10-42-52

To this:
screenshot from 2018-01-11 10-42-36

### CODE REVIEW

**Comment by lestcape** [comment]
To be honest, i don't like to occupy more space on the panel and this is why is in that way.

So, i will wait for the opinion of more people about this without merged it for now.

**Comment by betorobson** [comment]
No  worries mate. You did a good job in this extension any way.

**Comment by kprinssu** [comment]
The after is much cleaner looking with the padding. The padding is small and doesn't really effect sizing all that much.

**Comment by yoshidf** [comment]
Please, would be nice get this merge

**Comment by lestcape** [comment]
@betorobson Thanks for your contribution....
@kprinssu and @yoshidf thanks for give us your opinions.

**Pull request merged**
