### PR TITLE
Spacing

### PR DESCRIPTION
**Pull request by dimitrov-adrian**
Add spacing between main items and use native sizing for top and bottom padding for sub-menues.

### CODE REVIEW

**Comment by lestcape** [comment]
Sorry if i ask an stupid thing, but i don' t know the priority of gnome shell to apply a theme. How have more priority? The applet style or the gnome shell style?

In case that will be the gnome style (like on cinnamon is actually), this will not break the possibility of add support to this extension by a third-party gnome-shell theme?

**Comment by dimitrov-adrian** [comment]
Yes your are right. Extensions are in top priority, but I don't think such spacing will hurt as it will do only for this extension.

**Comment by lestcape** [comment]
Yes this is what i say... This is only for this extension, so... If i set that, when some one are making a theme and he decide to add support to this extension and he don' t want to used the default extension values, he will need to overrides this values in the theme that he is creating, so when he do that this also will affected all others gnome shell actors that use this style class, but in other different actors do that could be an error, so  he sure will don't want to change this values then, making what you do a hard-coding style.

**Comment by lestcape** [comment]
I will try to see if i can add a parent class to be refrence so you could set your style in the way 
`.parent.chid {}` and not in the way you are setting it `.chid {}`, then as the parent is unique to this extension he can modify this style, without affected all other actors.

**Comment by lestcape** [comment]
There are an easy way to set the style from a gnome shell theme now and some important style class are set in the stylesheet.css file. Default style are is only for the default gnome shell theme and with the appearance of the default theme. Other themes need to define this in his way... If you want to add something directly to the default theme you can, but only if it's to be more close to the default gnome shell theme. If you want to have a different style for the menu items, this need to be request to the theme author instead of make it directly here...

**Pull request closed without merging**
