### PR TITLE
Add option to toggle overlayKey

### PR DESCRIPTION
**Pull request by Lesik**
This PR is open for edits, as I have no experience with GNOME Shell extensions.

### CODE REVIEW

**Comment by lestcape** [comment]
This have not sense... The keybinding is designed to be decided by the user, this is why is problematic, because can be customized. The reason of select by default the alt modifier is because is exactly the most problematic key and the real problem that need a fix. I don' t want to add a workaround i want a general mechanism that will work for the keybinding selected by the user not matter warever the user select.

**Comment by Lesik** [comment]
Yes, but while it doesn't exist yet, this could be a quick workaround that makes the extension usable. I can't use the extension at all because it breaks all other shortcuts that include alt. And there is no way to remove the alt shortcut.

**Comment by lestcape** [comment]
Follow this steps:

1- Right click inside the menu
2- In the popup menu left click in **configure...**
3- Scroll to the box **Main Menu**
4- Click inside the "**Alt**" shortcut, in the option **keyboard shorcut to open and close the menu**
5- Hit **Backspace** key.

Problem solved.

**Comment by Lesik** [comment]
@lestcape As I said in the #51: "[...] clicking the shortcut, then pressing escape to remove it, doesn't actually remove it for me"

**Comment by lestcape** [comment]
@Lesik please press **Backspace**, not **escape**

**Comment by lestcape** [comment]
**escape**, work as it should be.... Is for **scape** (_exit without modify anything_)... **backspace** is for delete the current keybinding.

**Comment by Lesik** [comment]
But is empty!

bildschirmfoto von 2017-07-22 17-13-31

I am not stupid...

**Comment by lestcape** [comment]
I don't say you are stupid... Yes is empty, this is not what you want? You don't want to disable the keybinding... Empty means not keybinding, mean is disabled.

**Comment by Lesik** [comment]
Yes but it still grabs Alt. Is not disabled.

**Comment by lestcape** [comment]
Oppss.... There are a problem then.... Because need to be disable... Is disable for me.

**Comment by lestcape** [comment]
In this line https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/settings/keybindingWidgets.js#L199

Gnome show a warning, maybe is not just a warring to you.
So change it to be:

```
    set_value: function(accel_string) {//accel_string=null
        if(!accel_string)
            accel_string = "";
        this.set_property("accel-string", accel_string);
    },
```
Maybe this will resolve the problem for you.

**Comment by lestcape** [comment]
To see the warning:

1- Open a terminal
2- Execute gnome-shell-extension-prefs
3- click on the settings of gnome global menu
4- Remove the alt key

You can added a ```global.log("message");``` after this line : https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/environment.js#L90

If the message is not printed, then you have right and the keybinding is steel garbed for you.

**Comment by lestcape** [comment]
@Lesik ohh yes, i don't know what occurs on wayland... The extension is not ready to be working on wayland.

**Pull request closed without merging**
